6 get /api/reviews/review id/comments
rovercode1/games-forum pull request #5
Opened 2023-02-22 10:57 UTC by rovercode1

2023-02-22 11:16 UTC, HannahBurks requested changes
Great work so far, just an error handling change as we want to utilising our PSQL errors which are automatically thrown. Do a .only on the 400 test and console log err in the error handler file - you should see the psql error if you try to put a string in as ID

2023-02-22 11:16 UTC, HannahBurks commented on __tests__/app.test.js
> +          // comments should be served with the most recent comments first
Lets remove this comment :)

2023-02-22 11:16 UTC, HannahBurks commented on models/comment-models.js
> +  if (regEx.test(parseInt(reviewId)) === false) {
If it is an invalid ID (such as a string) PSQL should automatically throw and error due to it breaking the sql type - you can then instead handle this error in your error handler by checking the psql error code :) We won't need to deal with it here, only the error from an id that does not exists such as 10000) - then we can do a promise .reject if we get no data back

2023-02-23 13:12 UTC, merged

2023-02-23 13:13 UTC, sirKevlar commented on __tests__/app.test.js
> +
We need one more happy path test here... There is a review in your data which has no associated comments. In this case, we would expect 200 and an empty array would be returned